version: "3.8"
services:
  timescale:
    image: timescale/timescaledb:latest-pg15
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_USER=hatchet
      - POSTGRES_PASSWORD=hatchet
      - POSTGRES_DB=hatchet
    ports:
      - "5432:5432"
    volumes:
      - hatchet_timescale_data:/var/lib/postgresql/data

volumes:
  hatchet_timescale_data:
