// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: copyfrom.go

package dbsqlc

import (
	"context"
)

// iteratorForBulkInsertLogs implements pgx.CopyFromSource.
type iteratorForBulkInsertLogs struct {
	rows                 []BulkInsertLogsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertLogs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertLogs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CreatedAt,
		r.rows[0].TenantID,
		r.rows[0].ResourceID,
		r.rows[0].Log,
	}, nil
}

func (r iteratorForBulkInsertLogs) Err() error {
	return nil
}

func (q *Queries) BulkInsertLogs(ctx context.Context, db DBTX, arg []BulkInsertLogsParams) (int64, error) {
	return db.CopyFrom(ctx, []string{"logs"}, []string{"created_at", "tenant_id", "resource_id", "log"}, &iteratorForBulkInsertLogs{rows: arg})
}
